services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file:
      - ./apps/reservations/.env
    command: npm run start:dev reservations
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
