# -------------------------------
# Development stage
# -------------------------------
FROM node:20-alpine AS development

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate --schema=apps/reservations/prisma/schema.prisma

# Build the project
RUN npm run build


# -------------------------------
# Production stage
# -------------------------------
FROM node:20-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install --only=production

# ✅ Copy the generated Prisma client
COPY --from=development /usr/src/app/node_modules/.prisma /usr/src/app/node_modules/.prisma
COPY --from=development /usr/src/app/node_modules/@prisma /usr/src/app/node_modules/@prisma
COPY --from=development /usr/src/app/node_modules/@prisma/client /usr/src/app/node_modules/@prisma/client

# ✅ Copy the built dist folder
COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/reservations/main.js"]
